spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt-auth-db
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
